[2025-04-13T00:30:03.956+0000] {processor.py:186} INFO - Started process (PID=10111) to work on /opt/airflow/dags/embedding_pipeline_dag.py
[2025-04-13T00:30:03.956+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/embedding_pipeline_dag.py for tasks to queue
[2025-04-13T00:30:03.957+0000] {logging_mixin.py:190} INFO - [2025-04-13T00:30:03.957+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/embedding_pipeline_dag.py
[2025-04-13T00:30:03.996+0000] {logging_mixin.py:190} INFO - [2025-04-13T00:30:03.991+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/embedding_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/embedding_pipeline_dag.py", line 10, in <module>
    from src.kushal.utils.config_utils import get_config
ModuleNotFoundError: No module named 'src.kushal'
[2025-04-13T00:30:03.998+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/embedding_pipeline_dag.py
[2025-04-13T00:30:04.016+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/embedding_pipeline_dag.py took 0.065 seconds
[2025-04-13T00:30:34.484+0000] {processor.py:186} INFO - Started process (PID=10180) to work on /opt/airflow/dags/embedding_pipeline_dag.py
[2025-04-13T00:30:34.485+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/embedding_pipeline_dag.py for tasks to queue
[2025-04-13T00:30:34.486+0000] {logging_mixin.py:190} INFO - [2025-04-13T00:30:34.486+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/embedding_pipeline_dag.py
[2025-04-13T00:30:34.510+0000] {logging_mixin.py:190} INFO - [2025-04-13T00:30:34.507+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/embedding_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/embedding_pipeline_dag.py", line 10, in <module>
    from src.kushal.utils.config_utils import get_config
ModuleNotFoundError: No module named 'src.kushal'
[2025-04-13T00:30:34.511+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/embedding_pipeline_dag.py
[2025-04-13T00:30:34.529+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/embedding_pipeline_dag.py took 0.049 seconds
[2025-04-13T00:31:04.682+0000] {processor.py:186} INFO - Started process (PID=10249) to work on /opt/airflow/dags/embedding_pipeline_dag.py
[2025-04-13T00:31:04.683+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/embedding_pipeline_dag.py for tasks to queue
[2025-04-13T00:31:04.684+0000] {logging_mixin.py:190} INFO - [2025-04-13T00:31:04.684+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/embedding_pipeline_dag.py
[2025-04-13T00:31:04.709+0000] {logging_mixin.py:190} INFO - [2025-04-13T00:31:04.706+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/embedding_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/embedding_pipeline_dag.py", line 10, in <module>
    from src.kushal.utils.config_utils import get_config
ModuleNotFoundError: No module named 'src.kushal'
[2025-04-13T00:31:04.710+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/embedding_pipeline_dag.py
[2025-04-13T00:31:04.729+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/embedding_pipeline_dag.py took 0.051 seconds
[2025-04-13T00:31:35.325+0000] {processor.py:186} INFO - Started process (PID=10318) to work on /opt/airflow/dags/embedding_pipeline_dag.py
[2025-04-13T00:31:35.326+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/embedding_pipeline_dag.py for tasks to queue
[2025-04-13T00:31:35.327+0000] {logging_mixin.py:190} INFO - [2025-04-13T00:31:35.327+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/embedding_pipeline_dag.py
[2025-04-13T00:31:35.354+0000] {logging_mixin.py:190} INFO - [2025-04-13T00:31:35.351+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/embedding_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/embedding_pipeline_dag.py", line 10, in <module>
    from src.kushal.utils.config_utils import get_config
ModuleNotFoundError: No module named 'src.kushal'
[2025-04-13T00:31:35.355+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/embedding_pipeline_dag.py
[2025-04-13T00:31:35.375+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/embedding_pipeline_dag.py took 0.056 seconds
[2025-04-13T00:32:05.967+0000] {processor.py:186} INFO - Started process (PID=10382) to work on /opt/airflow/dags/embedding_pipeline_dag.py
[2025-04-13T00:32:05.967+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/embedding_pipeline_dag.py for tasks to queue
[2025-04-13T00:32:05.968+0000] {logging_mixin.py:190} INFO - [2025-04-13T00:32:05.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/embedding_pipeline_dag.py
[2025-04-13T00:32:05.992+0000] {logging_mixin.py:190} INFO - [2025-04-13T00:32:05.989+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/embedding_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/embedding_pipeline_dag.py", line 10, in <module>
    from src.kushal.utils.config_utils import get_config
ModuleNotFoundError: No module named 'src.kushal'
[2025-04-13T00:32:05.994+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/embedding_pipeline_dag.py
[2025-04-13T00:32:06.011+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/embedding_pipeline_dag.py took 0.050 seconds
